export const formFields = [
  {
    fieldType: "text",
    fieldId: "name",
    fieldValue: "",
    defaultValue: "",
    fieldLabel: "Name",
    className: "",
    maxLength: "",
    minLength: "",
    required: true,
  },
  {
    fieldType: "dropdown",
    fieldId: "dd",
    fieldValue: "",
    defaultValue: "",
    fieldLabel: "Please select your Name",
    value: ["Ankit", "Sunil", "Rohit", "Gill"],
    dropdownvalue: ["Ankit", "Sunil", "Rohit", "Gill"],
    className: "",
    maxLength: "",
    minLength: "",
    required: true,
  },
  {
    fieldType: "radio",
    fieldId: "radio",
    fieldValue: "",
    defaultValue: "",
    fieldLabel: "email",
    className: "",
    maxLength: "",
    minLength: "",
    required: true,
  },
  {
    fieldType: "checkbox",
    fieldId: "phoneNumber",
    fieldValue: "",
    defaultValue: "",
    fieldLabel: "Phone Number",
    className: "",
    maxLength: "",
    minLength: "",
    required: false,
  },
];
