export const formFields = [
  {
    fieldType: "text",
    fieldId: "name",
    fieldValue: "",
    defaultValue: "",
    fieldLabel: "Name",
    className: "",
    maxLength: "",
    minLength: "",
    required: true,
  },
  {
    fieldType: "dropdown",
    fieldId: "dd",
    fieldValue: "",
    defaultValue: "",
    fieldLabel: "Please select your Dropdown",
    dropdownvalue: [
      { name: "Please select", value: "" },
      { name: "True", value: "true" },
      { name: "False", value: "false" },
    ],
    className: "",
    maxLength: "",
    minLength: "",
    required: true,
  },
  // {
  //   fieldType: "radio",
  //   fieldId: "radio",
  //   fieldValue: [
  //     { name: "True", value: true },
  //     { name: "False", value: false },
  //   ],
  //   defaultValue: true,
  //   fieldLabel: "Check your answer",
  //   className: "",
  //   maxLength: "",
  //   minLength: "",
  //   required: true,
  //   visibilty: false,
  //   dependentOn: "dd",
  // },
  // {
  //   fieldType: "checkbox",
  //   fieldId: "checkbox",
  //   fieldValue: [
  //     { name: "True", value: true },
  //     { name: "False", value: false },
  //   ],
  //   defaultValue: true,
  //   fieldLabel: "Check your answer",
  //   className: "",
  //   maxLength: "",
  //   minLength: "",
  //   required: false,
  //   visibilty: false,
  //   dependentOn: "dd",
  // },
];
